### ISSUE TITLE
git required

### ISSUE THREAD

**Issue by janroelofs** [fralau/mkdocs_macros_plugin#31] opened 2020-04-17 14:24 UTC
Since updating to 0.4.4 git seems to be required. Running without git installed:
```
Traceback (most recent call last):
 File "/usr/local/bin/mkdocs", line 8, in <module>
   sys.exit(cli())
 File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
   return self.main(*args, **kwargs)
 File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
   rv = self.invoke(ctx)
 File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
   return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
   return ctx.invoke(self.callback, **ctx.params)
 File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
   return callback(*args, **kwargs)
 File "/usr/local/lib/python3.6/site-packages/mkdocs/__main__.py", line 159, in build_command
   build.build(config.load_config(**kwargs), dirty=not clean)
 File "/usr/local/lib/python3.6/site-packages/mkdocs/commands/build.py", line 239, in build
   config = config['plugins'].run_event('config', config)
 File "/usr/local/lib/python3.6/site-packages/mkdocs/plugins.py", line 94, in run_event
   result = method(item, **kwargs)
 File "/usr/local/lib/python3.6/site-packages/macros/plugin.py", line 309, in on_config
   define_env(self)
 File "/usr/local/lib/python3.6/site-packages/macros/context.py", line 239, in define_env
   env.variables['git'] = get_git_info()
 File "/usr/local/lib/python3.6/site-packages/macros/context.py", line 148, in get_git_info
   universal_newlines=True).strip()
 File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
   **kwargs).stdout
 File "/usr/lib64/python3.6/subprocess.py", line 423, in run
   with Popen(*popenargs, **kwargs) as process:
 File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__
   restore_signals, start_new_session)
 File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
   raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git': 'git'
```
I could not find the requirement in the docs, and version 0.2.4 did not require git.

**Comment by rutgervaneijden** [comment] 2020-04-19 11:13
I have a similar issue. Any advise how to solve this?

`
[macros] Macros arguments: {'module_name': 'main', 'include_dir': '', 'include_yaml': [], 'j2_block_start_string': '', 'j2_block_end_string': '', 'j2_variable_start_string': '', 'j2_variable_end_string': ''}
Traceback (most recent call last):
  File "/home/pi/.local/bin/mkdocs", line 10, in <module>
    sys.exit(cli())
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/mkdocs/__main__.py", line 159, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/home/pi/.local/lib/python3.7/site-packages/mkdocs/commands/build.py", line 239, in build
    config = config['plugins'].run_event('config', config)
  File "/home/pi/.local/lib/python3.7/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/macros/plugin.py", line 309, in on_config
    define_env(self)
  File "/home/pi/.local/lib/python3.7/site-packages/macros/context.py", line 239, in define_env
    env.variables['git'] = get_git_info()
  File "/home/pi/.local/lib/python3.7/site-packages/macros/context.py", line 148, in get_git_info
    universal_newlines=True).strip()
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git': 'git'
`

**Comment by fralau** [comment] 2020-04-27 15:03
Duplicate of #30

**Comment by fralau** [comment] 2020-04-29 12:20
Has your issue been solved?

**Comment by rutgervaneijden** [comment] 2020-04-29 16:38
In a sense yes, I installed git. Although I’m not using git.

 

Thank you for asking, kind regards,

Rutger

**Comment by fralau** [comment] 2020-04-30 07:57
Thanks, I believe we can close this usse.

**Closed** 2020-04-30 07:58 UTC
Labels: duplicate

**Comment by janroelofs** [comment] 2020-04-30 08:00
I also circumvented it by adding git. Still planning to test the fix without git sometime but I agree to closing the issue. Thanks for the quick response.

**Comment by trogper** [comment] 2020-05-12 17:45
When is this going to be on pypi? I'm considering whether to use 0.3.3 in CI/pipeline or wait for 0.4.7

**Comment by fralau** [comment] 2020-05-13 07:30
Thanks for the reminder. 0.4.7 Is now on pypi.
